version: '3.6'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: .
    command: run_dev_server
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build: ./frontend
    environment:
      env_file: .env
      NODE_ENV: development
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  postgres_data:
